# Generated by Django 4.1.3 on 2022-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_blog_is_active_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='majority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='user/defaauluser.png', upload_to=''),
        ),
    ]
