# Generated by Django 4.1.3 on 2022-12-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='author_id',
        ),
    ]
