# Generated by Django 4.1.3 on 2022-12-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_author_message_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author_id',
            new_name='author',
        ),
    ]
