# Generated by Django 4.1.3 on 2022-12-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_author_id_message_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='writte_at',
            new_name='written_at',
        ),
    ]
