# Generated by Django 4.1.3 on 2022-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_blog_options_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
