# Generated by Django 4.1.3 on 2022-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_blogviewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogviewing',
            name='viewed_at_date',
            field=models.DateField(auto_now=True),
        ),
    ]
