# Generated by Django 4.1.3 on 2022-12-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_blogviewing_viewed_at_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogviewing',
            old_name='viewed_at_date',
            new_name='viewed_date',
        ),
        migrations.RemoveField(
            model_name='blogviewing',
            name='viewed_at',
        ),
    ]
