# Generated by Django 4.1.3 on 2022-12-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_comment_blogviewing_viewed_time_alter_blog_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.CharField(choices=[('active', 'active'), ('cancel', 'cancel'), ('pending', 'pending')], default='pending', max_length=8),
        ),
    ]
