# Generated by Django 4.1.3 on 2022-12-13 11:07
import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
