# Generated by Django 4.1.3 on 2022-12-14 12:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_message_answer_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
